# This file was generated by GoReleaser. DO NOT EDIT.
cask "homa" do
  version "0.2.2"

  on_macos do
    on_arm do
      sha256 "c52625f28528063387b00abbc42c622e42267ec8d7dd085d8154aefeb433be92"
      url "https://github.com/Serajian/homa/releases/download/v#{version}/homa_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "30ec87027c233f034c11036ba7b00f10184938a479861f7de20bcbdd23550000"
      url "https://github.com/Serajian/homa/releases/download/v#{version}/homa_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "852a356263816f06237f9c15bf7de9daf90c558d23a011afd818efb12119cea5"
      url "https://github.com/Serajian/homa/releases/download/v#{version}/homa_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e5743cbedafa892516d1714fa957c4f62d857554a98ab9f53ca8601b693e8a09"
      url "https://github.com/Serajian/homa/releases/download/v#{version}/homa_#{version}_linux_amd64.tar.gz"
    end
  end

  name "homa"
  desc "Peer-to-peer terminal chat with file transfer. No server, no account."
  homepage "https://github.com/Serajian/homa"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "homa"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/homa"]
    end
  end

  # No zap stanza required
end
