# This file was generated by GoReleaser. DO NOT EDIT.
cask "homa" do
  version "0.2.5"

  on_macos do
    on_arm do
      sha256 "cf0c6aef21b970cdc9353d42f6a1b71139881417cc094ef2ef0f0c483f161e6c"
      url "https://github.com/Serajian/homa/releases/download/v#{version}/homa_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "6110f0d7150a9b498578895708d49baab7545629f52659acb7709778ca8f9c64"
      url "https://github.com/Serajian/homa/releases/download/v#{version}/homa_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b8dbaf7d8e8fbc2dee0509873f161552e4adac1b4c82cea3bc0877591e791b3b"
      url "https://github.com/Serajian/homa/releases/download/v#{version}/homa_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ed8674ac611900f52c5b409db5661b97f7f761a0b3395ce18328294e53eb8f5d"
      url "https://github.com/Serajian/homa/releases/download/v#{version}/homa_#{version}_linux_amd64.tar.gz"
    end
  end

  name "homa"
  desc "Peer-to-peer terminal chat with file transfer. No server, no account."
  homepage "https://github.com/Serajian/homa"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "homa"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/homa"]
    end
  end

  # No zap stanza required
end
