# This file was generated by GoReleaser. DO NOT EDIT.
cask "homa" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "73ad62c61610a9cccd7c443420ab21f4971b36f38bf1d0d9ed79fab05a9f4a0a"
      url "https://github.com/Serajian/homa/releases/download/v#{version}/homa_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "856fc87146781fee37d85f1c069ca377c2b17e4d515a923e9d07c541915ea42d"
      url "https://github.com/Serajian/homa/releases/download/v#{version}/homa_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "38d4035d4fd872105599c2b6c45e046fc8304cb7f84e7da09c97ccf8481bb7df"
      url "https://github.com/Serajian/homa/releases/download/v#{version}/homa_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "87f604b6d01a2702b3394215f79e2da8d8cbd6cc0d15b061fe85e89c99268b72"
      url "https://github.com/Serajian/homa/releases/download/v#{version}/homa_#{version}_linux_amd64.tar.gz"
    end
  end

  name "homa"
  desc "Peer-to-peer terminal chat with file transfer. No server, no account."
  homepage "https://github.com/Serajian/homa"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "homa"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/homa"]
    end
  end

  # No zap stanza required
end
